name: Trigger Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call check availability endpoint
        run: |
          curl -X GET "${{ secrets.CRON_URL }}${{ secrets.CRON_ENDPOINT }}"
