name: Trigger Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron job
        run: |
          curl -X GET "${{ secrets.CRON_URL }}${{ secrets.CRON_ENDPOINT }}"
